version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # TODO: Move to .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=app_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
